sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 862482
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tSXGSt4EtkdRL4obo7k
    access-key-secret: jD7HuyRzO0uHKyGYRhYcsXNKkmPCSr
    bucket-name: sky-itcast-zhensi
  redis:
    host: localhost
    port: 6379
    password: 862482
    database: 10
  wechat:
    appid: wxbb5bfe6df31d258c
    secret: 589db7bc4a682e1fe35059b6450b30d4

